# fly.toml app configuration file generated for dicer on 2024-05-06T13:02:21+01:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.

app = 'dicer'
primary_region = 'iad'

[build]

[processes]
  app = 'task prod'

[http_service]
  internal_port = 8000
  force_https = true
  auto_stop_machines = true
  auto_start_machines = true
  min_machines_running = 0
  processes = ['app']

[[vm]]
  size = 'shared-cpu-1x'
